version: 2.1

jobs:
  build-and-test:  
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          working_directory: ~/project/App.Tests
          name: Run tests
          command: |
            dotnet test
            

workflows:
  sample: 
    jobs:
      - build-and-test
