version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:

  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run: 
          name: build
          command: |
            msbuild App.Android/App.Android.csproj "/p:Configuration=CI" "/t:PackageForAndroid"

workflows:
  version: 2
  build_and_upload_artifact:
    jobs:
      - build