version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project
          name: Build Android
          command: |
            msbuild App.Android/App.Android.csproj "/p:Configuration=CI" "/t:PackageForAndroid"
            

workflows:
  sample: 
    jobs:
      - build-and-test
