version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
          working_directory: ~/project
          name: Build Android
          command: |
            msbuild App.Android/App.Android.csproj "/p:Configuration=CI" "/t:PackageForAndroid"
            

workflows:
  sample: 
    jobs:
      - build-and-test
