version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:

  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - run: 
          name: build
          command: |
            nuget restore
            msbuild TestesComTestes.Android/TestesComTestes.Android.csproj

workflows:
  version: 2
  build_and_upload_artifact:
    jobs:
      - build