version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
          working_directory: ~/project/App.Tests
          name: Run tests
          command: |
            dotnet test
            

workflows:
  sample: 
    jobs:
      - build-and-test
